[functions.register-user]
verify_jwt = false

[functions.generate-invite]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.grant-gm-role]
verify_jwt = false

[functions.extend-invite]
verify_jwt = false

[functions.delete-invite]
verify_jwt = false

[functions.preview-invite]
verify_jwt = false

[functions.gm-delete-user]
verify_jwt = false

[functions.gm-reset-user-password]
verify_jwt = false